### ISSUE TITLE
Issues 0.1 

### ISSUE THREAD

**Issue by Bigguysahaj** [whole-earth/campus-explore#3]
## Sprint 1
This todo list is for the left over requirements and clean up for Sprint 1, to be performed at the end of major Sprint 1 tasks.

### TODO LIST
- [ ] Fix the highligting hover text on the points
- [ ] Add a movable divider between middlebar and scatterplot
- [ ] Fix scatter-plot and visualizer options
- [ ] Figure out dark theme
- [ ] Replace all img with Image once you are done

**Comment by Bigguysahaj** [comment]
The following options, don't always work.
Have to see if it's related to a react issue or the main project issue
![image](https://github.com/whole-earth/campus-explore/assets/70798888/4dbac34e-18cb-40bd-8862-abc1793b80b3)


Along with it, would need to work on recognizing why the labels/titles stray so far away from the point and what should be a proper place or way for it to be shown
![image](https://github.com/whole-earth/campus-explore/assets/70798888/3236d77d-d1cd-497f-ac2a-237ff563da1b)

**Comment by whole-earth** [comment]
We can create an html div with a <p> whose `innerHTML` we modify on hover events.
And when no element is hovered, hide the entire card.
![Hover Mockup](https://github.com/whole-earth/campus-explore/assets/67808476/a4a04edf-12d9-4a5f-98b6-cfb2d84840c8)

**Comment by Bigguysahaj** [comment]
Okay Noted, thanks for the mockup!!
